### GET all todos
http://localhost:8000/api/todos

### GET all categories
http://localhost:8000/api/categories

### GET a single todo
http://localhost:8000/api/todos/5

### GET a single category
http://localhost:8000/api/categories/4

### DELETE a todo
DELETE http://localhost:8000/api/todos/2

### DELETE a category
DELETE http://localhost:8000/api/categories/4

### POST a new todo
POST http://localhost:8000/api/todos
Content-Type: application/json

{
    "name": "New Todo 27",
    "category_id": 2,
    "status": "In Progress"
}

### POST a new category
POST http://localhost:8000/api/categories
Content-Type: application/json

{
    "category": "New Category 6"
}

### PUT a Todo
PUT http://localhost:8000/api/todos/2
Content-Type: application/json

{
    "name": "PUT Test",
    "category_id": 3,
    "status": "In Progress"
}

### PUT a category
PUT http://localhost:8000/api/categories/4
Content-Type: application/json

{
    "category": "New 4"
}
